name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
      - 'feature-*'

permissions:
  contents: write
  id-token: write

jobs:
  feature-check:
    if: startsWith(github.ref, 'refs/heads/feature-')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install frontend & backend dependencies
        run: |
          cd frontend && yarn install && cd ..
          cd backend1 && yarn install && cd ..
          cd backend2 && yarn install && cd ..

      - name: Run frontend & backend build check
        run: |
          cd frontend && yarn build && cd ..
          cd backend1 && yarn start & sleep 5 && kill $! && cd ..
          cd backend2 && yarn start & sleep 5 && kill $! && cd ..

  build-and-push-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    env:
      TAG: dev

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: DockerHub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.CICD_USERNAME }}
          password: ${{ secrets.CICD_PASSWORD }}

      - name: Build and push backend1
        uses: docker/build-push-action@v5
        with:
          context: ./backend1
          push: true
          tags: ${{ secrets.CICD_USERNAME }}/backend1:${{ env.TAG }}

      - name: Build and push backend2
        uses: docker/build-push-action@v5
        with:
          context: ./backend2
          push: true
          tags: ${{ secrets.CICD_USERNAME }}/backend2:${{ env.TAG }}

      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.CICD_USERNAME }}/frontend:${{ env.TAG }}

  build-and-push-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      TAG: prod
    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: DockerHub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.CICD_USERNAME }}
          password: ${{ secrets.CICD_PASSWORD }}

      - name: Build and push backend1 (prod)
        uses: docker/build-push-action@v5
        with:
          context: ./backend1
          push: true
          tags: ${{ secrets.CICD_USERNAME }}/backend1:${{ env.TAG }}

      - name: Build and push backend2 (prod)
        uses: docker/build-push-action@v5
        with:
          context: ./backend2
          push: true
          tags: ${{ secrets.CICD_USERNAME }}/backend2:${{ env.TAG }}

      - name: Build and push frontend (prod)
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.CICD_USERNAME }}/frontend:${{ env.TAG }}
